sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - bower_components
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

script:
  - gulp lint
  - gemini test test/visual
  - travis_retry xvfb-run -s '-screen 0 1024x768x24' wct
  - travis_retry xvfb-run -s '-screen 0 1024x768x24' wct --dom=shadow
